male(george).
male(michael).
male(roger).
male(david).
male(nick).
male(denis).
male(tom).
male(henry).
male(bill).
male(martin).

female(mary).
female(martha).
female(hannah).
female(rachel).
female(judie).
female(laura).
female(sue).
female(sandra).
female(ann).



parent(mary,michael).
parent(mary,tom).
parent(mary,laura).
parent(george,michael).
parent(george,tom).
parent(george,laura).
parent(martha,hannah).
parent(martha,rachel).
parent(martha,david).
parent(michael,hannah).
parent(michael,rachel).
parent(michael,david).
parent(rachel,judie).
parent(rachel,nick).
parent(rachel,denis).
parent(roger,judie).
parent(roger,nick).
parent(roger,denis).
parent(laura,bill).
parent(laura,sue).
parent(henry,bill).
parent(henry,sue).
parent(sue,sandra).
parent(sue,ann).
parent(martin,sandra).
parent(martin,ann).
